name: bankingapplication
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  age: ^0.0.1
  pattern_formatter: ^1.0.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^2.2.0
  rflutter_alert: ^1.0.3
  email_validator: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: AlfaSlabOne
      fonts:
        - asset: fonts/AlfaSlabOne-Regular.ttf
    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
